<a href="https://colab.research.google.com/github/salsarizky/Mechinelerning/blob/main/SalsaML3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd

In [2]:
#DATA TRAINING
data = {
    "X1": [40, 50, 50, 70, 80, 60],
    "X2": [5, 8, 7, 4, 4, 6],
    "X3": [60, 40, 30, 60, 80, 60],
    "Y": ["TOLAK", "TERIMA", "TOLAK", "TERIMA", "TERIMA", "TERIMA"]
}

df = pd.DataFrame(data)

print("Data Training:")
display(df)

Data Training:

   X1  X2  X3       Y
0  40   5  60   TOLAK
1  50   8  40  TERIMA
2  50   7  30   TOLAK
3  70   4  60  TERIMA
4  80   4  80  TERIMA
5  60   6  60  TERIMA

In [3]:
#LABEL
X = df[["X1", "X2", "X3"]].values
y = df["Y"].values

In [4]:
#DATA BARU
data_baru = np.array([[50, 3, 40]])

In [5]:
#HITUNG JARAK EUCLIDEAN
jarak = np.sqrt(np.sum((X - data_baru) ** 2, axis=1))

hasil_jarak = df.copy()
hasil_jarak["Jarak"] = jarak
hasil_jarak = hasil_jarak.sort_values("Jarak")

print("\nHasil Perhitungan Jarak:")
display(hasil_jarak)

Hasil Perhitungan Jarak:

   X1  X2  X3       Y      Jarak
1  50   8  40  TERIMA   5.000000
2  50   7  30   TOLAK  10.770330
0  40   5  60   TOLAK  22.449944
5  60   6  60  TERIMA  22.561028
3  70   4  60  TERIMA  28.301943
4  80   4  80  TERIMA  50.009999

In [6]:
#PRREDIKSI K = 2
knn2 = KNeighborsClassifier(n_neighbors=2)
knn2.fit(X, y)
hasil_k2 = knn2.predict(data_baru)

In [7]:
#PREDIKSI K = 5
knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(X, y)
hasil_k5 = knn5.predict(data_baru)

print("\nHasil Prediksi K=2")
print("Status Pinjaman =", hasil_k2[0])

print("\nHasil Prediksi K=5")
print("Status Pinjaman =", hasil_k5[0])

print("\nKesimpulan:")
print("K=2 :", hasil_k2[0])
print("K=5 :", hasil_k5[0])

Hasil Prediksi K=2
Status Pinjaman = TERIMA

Hasil Prediksi K=5
Status Pinjaman = TERIMA

Kesimpulan:
K=2 : TERIMA
K=5 : TERIMA